% Define segment lengths and angles
L1 = 0.2; % length of segment 1
L2 = 0.3; % length of segment 2
L3 = 0.25; % length of segment 3
theta1 = pi/6; % angle of segment 1 relative to global x-axis
theta2 = pi/4; % angle of segment 2 relative to segment 1
theta3 = pi/3; % angle of segment 3 relative to segment 2
k1 = 0.5; % curvature of segment 1
k2 = -0.8; % curvature of segment 2
k3 = 0.7; % curvature of segment 3

% Compute the transformation matrix
T = eye(4); % initialize the transformation matrix
% Add the first segment transformation
T = T * [cos(theta1), -sin(theta1), 0, 0; ...
         sin(theta1), cos(theta1), 0, 0; ...
         0, 0, 1/k1, 0; ...
         0, 0, 0, 1];
% Add the second segment transformation
T = T * [cos(theta2), -sin(theta2), 0, L1; ...
         sin(theta2), cos(theta2), 0, 0; ...
         0, 0, 1/k2, 0; ...
         0, 0, 0, 1];
% Add the third segment transformation
T = T * [cos(theta3), -sin(theta3), 0, L2; ...
         sin(theta3), cos(theta3), 0, 0; ...
         0, 0, 1/k3, 0; ...
         0, 0, 0, 1];
% Add the final translation
T = T * [1,0,0,L3; ...
         0,1,0,0; ...
         0,0,1,0; ...
         0,0,0,1];